'use client';
import Image from 'next/image';
import { useEffect, useRef, useState } from 'react';
import { Icon } from './icons';
import { diagnosticQuestions, estimateLevel, proposeRoadmap } from '@/domain/onboarding';
import type { RoadmapStep, WorkspacePreferences } from '@/domain/platform';

type Voice = {lang:string;interimResults:boolean;onresult:((e:{results:ArrayLike<ArrayLike<{transcript:string}>>})=>void)|null;onerror:(()=>void)|null;onend:(()=>void)|null;start():void;abort():void};
export function Onboarding({preferences,onSave,onClose}:{preferences:WorkspacePreferences;onSave:(values:Partial<WorkspacePreferences>)=>Promise<void>;onClose:()=>void}){
 const [step,setStep]=useState(0),[name,setName]=useState(preferences.displayName),[age,setAge]=useState(preferences.ageConfirmed),[index,setIndex]=useState(0),[answers,setAnswers]=useState<number[]>([]),[selection,setSelection]=useState<number|null>(null),[goal,setGoal]=useState(preferences.goal),[situation,setSituation]=useState(preferences.targetSituation),[challenge,setChallenge]=useState(preferences.challenge),[topics,setTopics]=useState(preferences.topics),[minutes,setMinutes]=useState(preferences.dailyGoalMinutes),[plan,setPlan]=useState<RoadmapStep[]>([]),[listening,setListening]=useState(false),[message,setMessage]=useState(''),[saving,setSaving]=useState(false);
 const voice=useRef<Voice|null>(null);
 useEffect(()=>()=>{voice.current?.abort();window.speechSynthesis?.cancel()},[]);
 const question=diagnosticQuestions[index]!,score=answers.filter((a,i)=>diagnosticQuestions[i]!.answer===a).length,level=estimateLevel(score,answers.length);
 function say(text:string,lang='ja-JP'){window.speechSynthesis?.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=lang;window.speechSynthesis?.speak(u)}
 function listen(){const ctor=(window as unknown as {SpeechRecognition?:new()=>Voice;webkitSpeechRecognition?:new()=>Voice}).SpeechRecognition??(window as unknown as {webkitSpeechRecognition?:new()=>Voice}).webkitSpeechRecognition;if(!ctor){setMessage('このブラウザでは音声入力に対応していません。文字で回答できます。');return}voice.current?.abort();const v=new ctor();v.lang='ja-JP';v.interimResults=false;v.onresult=e=>{const value=e.results[0]?.[0]?.transcript??'';if(step===2)setGoal(value);if(step===3)setSituation(value);if(step===4)setChallenge(value)};v.onerror=()=>setMessage('マイクを利用できませんでした。文字入力でも続けられます。');v.onend=()=>setListening(false);voice.current=v;setListening(true);try{v.start()}catch{setListening(false)}}
 async function submit(){setSaving(true);try{await onSave({displayName:name.trim(),ageConfirmed:age,onboardingCompleted:true,goal,targetSituation:situation,challenge,topics,dailyGoalMinutes:minutes,cefr:level,roadmap:plan,roadmapApproved:true});onClose()}catch{setMessage('保存できませんでした。接続を確認して、もう一度お試しください。')}finally{setSaving(false)}}
 return <section className="onboard-page" aria-label="学習プランの設定"><header className="flow-header"><button className="icon-button" onClick={onClose} aria-label="設定を閉じる"><Icon name="close"/></button><div className="tiny-brand">lingoflow<span/></div><small>{step+1} / 7</small></header><div className="flow-track"><span style={{width:`${(step+1)/7*100}%`}}/></div><div className="onboard-content">
 {step===0&&<><Image unoptimized width={512} height={512} className="onboard-mascot" src="/brand/lingoflow-companion.png" alt="ヘッドホンをつけた水滴の相棒"/><p className="eyebrow">YOUR OWN LEARNING JOURNEY</p><h1>あなたの「話したい」から、<br/>はじめよう。</h1><p>まずは今のレベルと、叶えたいことを教えてください。</p><label className="field-label">呼び名（任意）<input value={name} maxLength={40} onChange={e=>setName(e.target.value)} placeholder="どのようにお呼びしましょう？"/></label><label className="check-field"><input type="checkbox" checked={age} onChange={e=>setAge(e.target.checked)}/>13歳以上です</label><button disabled={!age} className="primary wide" onClick={()=>setStep(1)}>簡易診断をはじめる <Icon name="arrow"/></button><small className="support-note">英語 / 日本語サポートで開始します。約5分・18問の参考診断です。</small></>}
 {step===1&&<><p className="eyebrow">A LITTLE CHECK-IN · {index+1} / {diagnosticQuestions.length}</p><h1>今のあなたに、<br/>ちょうどいいところから。</h1><span className="soft-tag">{question.kind}</span><h2 className="diagnostic-prompt">{question.prompt}</h2>{question.spoken&&<><button className="secondary" onClick={()=>say(question.spoken!,'en-US')}><Icon name="headphones"/>音声を聞く</button><details className="support-note"><summary>音声を再生できないとき</summary><p>この項目は「わからない」を選べます。音声が使える端末で再診断してください。</p></details></>}<div className="answer-grid">{question.options.map((o,i)=><button className={`answer-option ${selection===i?'is-selected':''}`} key={o} onClick={()=>setSelection(i)}>{o}{selection===i&&<Icon name="check"/>}</button>)}<button className={`answer-option muted ${selection===-1?'is-selected':''}`} onClick={()=>setSelection(-1)}>まだわからない</button></div><button className="primary wide" disabled={selection===null} onClick={()=>{setAnswers([...answers,selection!]);setSelection(null);if(index<diagnosticQuestions.length-1)setIndex(index+1);else setStep(2)}}>次へ <Icon name="arrow"/></button></>}
 {step>=2&&step<=4&&<><Image unoptimized width={512} height={512} className="question-mascot" src="/brand/lingoflow-companion.png" alt=""/><p className="eyebrow">LET’S MAKE IT PERSONAL</p><span className="soft-tag">参考レベル {level} · 話す力は未判定</span><h1>{step===2?'英語で、どんなことができるようになりたいですか？':step===3?(/旅行|海外|カフェ/.test(goal)?'その旅行では、どんな場面で話したいですか？':'どんな場面で、誰と話してみたいですか？'):'いま、いちばん難しいと感じることは？'}</h1><p>{step===2?'好きなテーマや、ちょっとした憧れでも大丈夫。':step===3?'目標に合ったプランを考えるための、追加質問です。':'聞き取り、言葉が出ない、文法など、自由に教えてください。'}</p><textarea autoFocus value={step===2?goal:step===3?situation:challenge} maxLength={500} onChange={e=>step===2?setGoal(e.target.value):step===3?setSituation(e.target.value):setChallenge(e.target.value)} placeholder="ここに入力してください" rows={4}/><button className="secondary wide" onClick={listen}><Icon name="mic"/>{listening?'聞いています…':'音声で答える'}</button><p className="support-note">音声認識はブラウザのサービスを使用します。録音は保存しません。</p><button className="primary wide" disabled={!(step===2?goal:step===3?situation:challenge).trim()} onClick={()=>{voice.current?.abort();setStep(step+1)}}>次へ <Icon name="arrow"/></button></>}
 {step===5&&<><p className="eyebrow">MAKE ROOM FOR A LITTLE ENGLISH</p><h1>好きなことを、<br/>毎日の習慣に。</h1><p>気になるテーマを選んでください。</p><div className="chips wrap">{['日常・Vlog','旅行','映画・文化','カフェ','仕事','テクノロジー','自然・動物','音楽'].map(t=><button key={t} className={topics.includes(t)?'selected':''} onClick={()=>setTopics(topics.includes(t)?topics.filter(x=>x!==t):[...topics,t])}>{t}</button>)}</div><label className="field-label">1日の学習時間<select value={minutes} onChange={e=>setMinutes(Number(e.target.value) as typeof minutes)}>{[5,10,15,20,30].map(m=><option key={m} value={m}>{m}分</option>)}</select></label><button className="primary wide" onClick={()=>{setPlan(proposeRoadmap(goal,topics));setStep(6)}}>プラン案を見る <Icon name="arrow"/></button></>}
 {step===6&&<><p className="eyebrow">A PATH MADE FOR YOU</p><h1>一歩ずつ、<br/>話したい自分へ。</h1><p className="goal-summary">{goal}</p><div className="plan-review">{plan.map((s,i)=><label key={s.id}><span>{i+1}</span><div><input aria-label={`目標${i+1}`} value={s.title} onChange={e=>setPlan(plan.map(p=>p.id===s.id?{...p,title:e.target.value}:p))}/><p>{s.description}</p></div></label>)}</div><p className="support-note">現在は選んだ内容から作るおすすめプランです。AIとの自由対話・自動生成は接続準備中。変更はこの画面で確認してから反映します。</p><button className="primary wide" onClick={()=>void submit()} disabled={saving||plan.some(s=>!s.title.trim())}>{saving?'保存しています…':'このプランではじめる'}<Icon name="check"/></button></>}
 {message&&<p role="status" className="notice">{message}</p>}{step>1&&<button className="text-button" onClick={()=>setStep(step-1)}>ひとつ戻る</button>}</div></section>
}
