import type { VideoMaterial } from "./types";
export const sampleMaterial: VideoMaterial = {
  id: "material-me-at-the-zoo-v1",
  youtubeVideoId: "jNQXAC9IVRw",
  title: "Me at the zoo",
  channelTitle: "jawed",
  learningLanguage: "en",
  captionSource: "admin",
  captionVersion: "internal-fixture-v1",
  phrases: [
    {
      id: "phrase-1",
      materialId: "material-me-at-the-zoo-v1",
      startMs: 0,
      endMs: 1350,
      replayPrerollMs: 700,
      text: "All right,",
      translation: "さて、",
    },
    {
      id: "phrase-2",
      materialId: "material-me-at-the-zoo-v1",
      startMs: 1350,
      endMs: 2600,
      replayPrerollMs: 700,
      text: "so here we are",
      translation: "今いるのは、",
    },
    {
      id: "phrase-3",
      materialId: "material-me-at-the-zoo-v1",
      startMs: 2600,
      endMs: 6900,
      replayPrerollMs: 700,
      text: "in front of the elephants.",
      translation: "ゾウたちの目の前です。",
    },
    {
      id: "phrase-4",
      materialId: "material-me-at-the-zoo-v1",
      startMs: 7000,
      endMs: 12800,
      replayPrerollMs: 700,
      text: "They have really, really, really long trunks.",
      translation: "本当に、本当に、とても長い鼻があります。",
    },
    {
      id: "phrase-5",
      materialId: "material-me-at-the-zoo-v1",
      startMs: 15000,
      endMs: 18900,
      replayPrerollMs: 700,
      text: "And that's pretty much all.",
      translation: "そして、だいたいそれくらいです。",
    },
  ],
};
